server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    driver-classname: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/registration
    username: root
    password: Abdo.workbench@55

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show_sql: true

  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connection timeout: 5000
          timeout: 3000
          write timeout: 5000